name: publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Build
        run: npm run build
      - run: |
          echo @kyndryl-design-system:https://npm.pkg.github.kyndryl.net/ > dist/.npmrc
          echo '//npm.pkg.github.kyndryl.net/:_authToken=${NPM_TOKEN}' >> dist/.npmrc
      - run: npm publish
        working-directory: ./dist
        env:
          NPM_TOKEN: ${{ secrets.GH_TOKEN_PACKAGES }}
