name: update-tokens
on:
  push:
    branches:
      #   - main
      #   - beta
      #   - next
      - tokens
    paths:
      - 'tokens/**'
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      COMMIT_MSG: 'fix(tokens): automated token update'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      # - name: Install dependencies
      #   run: npm ci --legacy-peer-deps
      - name: Build css variables
        run: npm run build:tokens
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '$COMMIT_MSG'
      - name: Create pull request
        run: gh pr create --base next --head tokens --title '$COMMIT_MSG' --body 'Created by the update-tokens GitHub Actions workflow'
